// File generated by manual configuration with project e-learning-b183d
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunBSEelbFQfKJLpKnAQWS3zVITwn6mWg',
    appId: '1:625661482133:web:bc159000c1f9dcf608379c',
    messagingSenderId: '625661482133',
    projectId: 'e-learning-b183d',
    authDomain: 'e-learning-b183d.firebaseapp.com',
    storageBucket: 'e-learning-b183d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAunBSEelbFQfKJLpKnAQWS3zVITwn6mWg',
    appId: '1:625661482133:android:bc159000c1f9dcf608379c',
    messagingSenderId: '625661482133',
    projectId: 'e-learning-b183d',
    storageBucket: 'e-learning-b183d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunBSEelbFQfKJLpKnAQWS3zVITwn6mWg',
    appId: '1:625661482133:ios:bc159000c1f9dcf608379c',
    messagingSenderId: '625661482133',
    projectId: 'e-learning-b183d',
    storageBucket: 'e-learning-b183d.firebasestorage.app',
    iosBundleId: 'www.azizul.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAunBSEelbFQfKJLpKnAQWS3zVITwn6mWg',
    appId: '1:625661482133:ios:bc159000c1f9dcf608379c',
    messagingSenderId: '625661482133',
    projectId: 'e-learning-b183d',
    storageBucket: 'e-learning-b183d.firebasestorage.app',
    iosBundleId: 'www.azizul.com',
  );
}
